"$schema" = 'https://starship.rs/config-schema.json'

[aws]
symbol = " "
style = "bold fg:#FCA17D"

[directory]
read_only = " 󰌾"
style = "bold fg:#DA627D"

[git_branch]
symbol = " "
style = "bold fg:#6bd897"

[kubernetes]
disabled = false
style = "bold fg:#2596be"

[time]
disabled = true
time_format = '%H:%M:%S'
